version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  jobs:
    pre_build:
      - make purge generate


sphinx:
  builder: html
  configuration: tutorials/conf.py

python:
  install:
    - requirements: requirements.txt
    - requirements: requirements-dev.txt
