version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  jobs:
    pre_create_environment:
      - make setup purge generate


sphinx:
  builder: html
  configuration: tutorials/conf.py

